name: "Making Documentation"

on:
  push:
    branches: [main]

jobs:
  docs:
    name: Publish typedoc documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Generate typedoc
        run: npm run typedoc
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }},
          publish_dir: "./dist/docs"